language: rust
rust:
  - stable
cache: cargo
script:
  - cargo build
after_success:
  - echo "${DEPLOY_SERVER_PUBLIC_KEY}" | base64 --decode >> $HOME/.ssh/known_hosts
  - chmod +x approve.sh
  - eval "$(ssh-agent -s)"
  - echo "${DEPLOY_SSH_KEY}" | base64 --decode > /tmp/deploy_key.pem
  - chmod 600 /tmp/deploy_key.pem
  - ssh-add /tmp/deploy_key.pem
  - git remote add deploy $DEPLOY_HOST
  - ./approve.sh --key="${APPROVEAPI_KEY}" --user="@slack:multiapproval-test" --title="Deployment Request" --body="Deploy rust-actix-web-magic-link demo app? ${TRAVIS_COMMIT} ${TRAVIS_COMMIT_MESSAGE}" && git push deploy master